services:
  s2-app:
    image: prawee/strapi:latest
    container_name: 68-s2-app
    ports:
      - "${APP_PORT}:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASS}